export var GET_ACCOUNT_SETTINGS = "GET_ACCOUNT_SETTINGS";
export var CLEAR_ACCOUNT_SETTINGS = "CLEAR_ACCOUNT_SETTINGS";
export const SET_ACCOUNT_SETTINGS = 'SET_ACCOUNT_SETTINGS';
export const SET_ACCOUNT = 'SET_ACCOUNT';
export const SET_CHECKIN_LIST = 'SET_CHECKIN_LIST';
export const SET_TEAM = 'SET_TEAM';
